import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawn } from 'node:child_process'

const root = fileURLToPath(new URL('..', import.meta.url))
const parity = join(root, 'bin', 'dsh-plugin-parity.js')
const dock = join(root, 'bin', 'dsh-mini-utility-dock.js')

// The pin value is arbitrary here: the check compares the members' pins to EACH
// OTHER, and an exact version is what makes them meaningful.
const PIN = '0.0.0'

function run(script, ...args) {
  return new Promise((resolve) => {
    const child = spawn(process.execPath, [script, ...args], { cwd: root, stdio: ['ignore', 'pipe', 'pipe'] })
    let stdout = ''; let stderr = ''
    child.stdout.on('data', (chunk) => { stdout += chunk })
    child.stderr.on('data', (chunk) => { stderr += chunk })
    child.on('close', (code) => resolve({ code, stdout, stderr }))
  })
}

// A member repository, as small as the check needs it: the three generated
// blocks in `lib/shared.js`, then the plugin's own lines — its guard export, and
// a second helper that applies the same loopback criterion for a different gate.
// That last one is the shape the check must NOT flag (a plugin naming the
// credential its route demands is the real case), so the fixture carries one on
// purpose.
const scaffold = (repo) => [
  `// ${repo}: the host-side shared code, generated blocks first.`,
  `export const VERSION = '0.0.0'`,
  '',
  '// <dsh-loopback-helpers>',
  '// </dsh-loopback-helpers>',
  '',
  '// <dsh-host-guard>',
  '// </dsh-host-guard>',
  '',
  '// <dsh-host-http>',
  '// </dsh-host-http>',
  '',
  `export const ${repo}Guard = ({ policy, ...options } = {}) => bindGuard({`,
  '  ...options,',
  '  respond: sendJson,',
  '  policy',
  '})',
  '',
  'export const requestNeedsBearer = (req) => {',
  '  const peerLoopback = isLoopbackAddress(req.socket && req.socket.remoteAddress)',
  '  return !peerLoopback',
  '}',
  ''
].join('\n')

async function member(dir, repo) {
  await mkdir(join(dir, repo, 'lib'), { recursive: true })
  await writeFile(join(dir, repo, 'package.json'), JSON.stringify({
    name: repo,
    type: 'module',
    devDependencies: { 'dsh-mini-utility-dock': PIN }
  }, null, 2) + '\n', 'utf8')
  const file = join(dir, repo, 'lib', 'shared.js')
  await writeFile(file, scaffold(repo), 'utf8')
  // Fill the three blocks the way a consumer does, so the comparison runs on real
  // generated bytes rather than on a hand-written approximation of them.
  const synced = await run(dock, 'sync', file)
  assert.equal(synced.code, 0, synced.stderr)
  return file
}

test('members that embed the same blocks pass, and the new block is compared', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'dsh-parity-'))
  await member(dir, 'alpha')
  await member(dir, 'beta')

  const result = await run(parity, '--root', dir)
  assert.equal(result.code, 0, result.stdout + result.stderr)
  assert.match(result.stdout, /host HTTP glue: identical across alpha\/beta/)
  assert.match(result.stdout, /no enforcement outside the generated blocks/)
  assert.match(result.stdout, /no drift/)
})

// The drift this adds coverage for: one member hand-edits the embedded glue — the
// exact shape of "my replies lost no-store" that the block exists to prevent.
test('a member whose host-HTTP block differs is named, with the diff', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'dsh-parity-'))
  await member(dir, 'alpha')
  const beta = await member(dir, 'beta')
  const source = await readFile(beta, 'utf8')
  assert.ok(source.includes("'cache-control': 'no-store'"), 'the fixture embeds the real block')
  await writeFile(beta, source.replace("'cache-control': 'no-store'", "'cache-control': 'no-cache'"), 'utf8')

  const result = await run(parity, '--root', dir)
  assert.equal(result.code, 1)
  assert.match(result.stdout, /FAIL host HTTP glue: beta differ from alpha/)
  assert.match(result.stdout, /no-cache/)
  assert.match(result.stdout, /1 drift problem\(s\)/)
  // The other two blocks are still identical: the report is per block.
  assert.match(result.stdout, /ok   loopback predicates: identical/)
  assert.match(result.stdout, /ok   host guard: identical/)
})

test('a member that never re-ran sync is reported as missing the block', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'dsh-parity-'))
  await member(dir, 'alpha')
  const beta = await member(dir, 'beta')
  // The pre-migration state: the file still carries only the two older blocks.
  const without = await readFile(beta, 'utf8')
  await writeFile(beta, without.replace(/\/\/ <dsh-host-http>[\s\S]*?\/\/ <\/dsh-host-http>\n/, ''), 'utf8')

  const result = await run(parity, '--root', dir)
  assert.equal(result.code, 1)
  assert.match(result.stdout, /FAIL host HTTP glue: missing or malformed markers in beta/)
})

// The behavioral half of the check needs a factory per member, which only
// `--member` supplies; the fixture's guards are built from the embedded blocks, so
// this also proves the three blocks load together as one module.
test('--member compares decisions and honors the fleet bounds', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'dsh-parity-'))
  await member(dir, 'alpha')
  await member(dir, 'beta')

  const result = await run(parity, '--root', dir,
    '--member', 'alpha:alphaGuard', '--member', 'beta:betaGuard')
  assert.equal(result.code, 0, result.stdout + result.stderr)
  assert.match(result.stdout, /ok   decisions: \d+ cases agree across alpha\/beta/)
  assert.match(result.stdout, /fleet bounds: skipped/)
  assert.match(result.stdout, /no drift/)

  // `--fleet` names the one member that opts into the relaxed mode, so the check
  // that the relaxation stays bounded runs against its guard alone.
  const fleet = await run(parity, '--root', dir,
    '--member', 'alpha:alphaGuard', '--member', 'beta:betaGuard', '--fleet', 'alpha')
  assert.equal(fleet.code, 0, fleet.stdout + fleet.stderr)
  assert.match(fleet.stdout, /ok   fleet bounds: \d+ cases hold/)

  // A member that exports no guard is a diagnosis, not a stack trace.
  const broken = await run(parity, '--root', dir, '--member', 'alpha:noSuchGuard', '--member', 'beta:betaGuard')
  assert.equal(broken.code, 1)
  assert.match(broken.stdout, /does not export a usable noSuchGuard/)

  // `--fleet` naming a repository that is not a member is a boundary check that
  // never ran; it must fail, not report the "skipped" line as a pass.
  const misnamed = await run(parity, '--root', dir,
    '--member', 'alpha:alphaGuard', '--member', 'beta:betaGuard', '--fleet', 'gamma')
  assert.equal(misnamed.code, 1)
  assert.match(misnamed.stdout, /FAIL fleet bounds: --fleet gamma is not one of the --member repositories/)
  assert.doesNotMatch(misnamed.stdout, /ok   fleet bounds: skipped/)
})

// The enforcement scan reads the file as text with the generated blocks dropped,
// so it cannot tell code from prose unless it matches a code shape. A consumer
// documents why its second helper is NOT a second guard — and that explanation
// names the headers the guard inspects. Prose must not fail the check; reading a
// header or declaring a guard outside the block must.
test('prose that names a policy keyword passes, code that reads it fails', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'dsh-parity-'))
  await member(dir, 'alpha')
  const beta = await member(dir, 'beta')

  const append = async (lines) => {
    const source = await readFile(beta, 'utf8')
    await writeFile(beta, source + lines.join('\n') + '\n', 'utf8')
  }

  await append([
    '/**',
    ' * Why this is not the guard: it never writes a reply, and it decides the',
    ' * credential before the guard runs, so `sec-fetch-site: cross-site` and a',
    ' * foreign Origin are reasons the guard will report later, not here.',
    ' */'
  ])
  const documented = await run(parity, '--root', dir)
  assert.equal(documented.code, 0, documented.stdout + documented.stderr)
  assert.match(documented.stdout, /no enforcement outside the generated blocks/)

  await append(['', "const site = req.headers['sec-fetch-site']", 'if (site) deny(site)'])
  const duplicated = await run(parity, '--root', dir)
  assert.equal(duplicated.code, 1)
  assert.match(duplicated.stdout, /beta: reads Fetch Metadata outside the blocks/)
})

// The bracket read above is one Fetch Metadata shape; a destructuring read is the
// other, and the old bare-keyword version used to catch it while the bracket-only
// pattern missed it. The contrast to prove: a comment that merely names the header
// is still prose, but `const { 'sec-fetch-site': x } = req.headers` is enforcement.
test('a destructured Fetch Metadata read is reported; naming it in prose is not', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'dsh-parity-'))
  await member(dir, 'alpha')
  const beta = await member(dir, 'beta')
  const append = async (lines) => {
    const source = await readFile(beta, 'utf8')
    await writeFile(beta, source + lines.join('\n') + '\n', 'utf8')
  }

  await append(['', '// The guard, not this route, inspects `sec-fetch-site`; this only logs.'])
  const prose = await run(parity, '--root', dir)
  assert.equal(prose.code, 0, prose.stdout + prose.stderr)

  await append(['', "const { 'sec-fetch-site': fetchSite } = req.headers", 'if (fetchSite) deny(fetchSite)'])
  const destructured = await run(parity, '--root', dir)
  assert.equal(destructured.code, 1)
  assert.match(destructured.stdout, /beta: reads Fetch Metadata outside the blocks/)
})

// The redefinition pattern must catch an assignment but not a comparison. A repo
// that branches on the shared list (`LOOPBACK_HOSTNAMES === x`) is reading a
// decision the blocks already make, not redefining it, so the `=` must be
// distinguished from `==` / `===`.
test('LOOPBACK_HOSTNAMES compared is allowed, reassigned is reported', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'dsh-parity-'))
  await member(dir, 'alpha')
  const beta = await member(dir, 'beta')
  const append = async (lines) => {
    const source = await readFile(beta, 'utf8')
    await writeFile(beta, source + lines.join('\n') + '\n', 'utf8')
  }

  await append(['', 'export const known = (h) => LOOPBACK_HOSTNAMES === h'])
  const compared = await run(parity, '--root', dir)
  assert.equal(compared.code, 0, compared.stdout + compared.stderr)

  await append(['', 'LOOPBACK_HOSTNAMES = ["127.0.0.1"]'])
  const reassigned = await run(parity, '--root', dir)
  assert.equal(reassigned.code, 1)
  assert.match(reassigned.stdout, /beta: redefines LOOPBACK_HOSTNAMES/)
})
